const pool = require('../database/')

async function createAccountTable() {
    try {
        // Verificar si la tabla existe
        const checkTable = await pool.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'account'
            )
        `)

        if (!checkTable.rows[0].exists) {
            console.log('Creando tabla account...')
            // Crear la tabla account
            await pool.query(`
                CREATE TABLE account (
                    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    account_firstname character varying NOT NULL,
                    account_lastname character varying NOT NULL,
                    account_email character varying NOT NULL,
                    account_password character varying NOT NULL,
                    account_type character varying NOT NULL DEFAULT 'Client',
                    account_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    account_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT account_pkey PRIMARY KEY (account_id),
                    CONSTRAINT account_email_unique UNIQUE (account_email),
                    CONSTRAINT account_email_check CHECK (
                        account_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
                    )
                )
            `)
            console.log('Tabla account creada exitosamente')
        } else {
            console.log('La tabla account ya existe')
        }

    } catch (error) {
        console.error('Error al crear la tabla account:', error)
    }
}

// Ejecutar la función
createAccountTable() 